Fix scraping semester code error
ftisunpar/IFStudentPortal pull request #59
Opened 2020-09-30 03:26 UTC by davidatz285

1. Merubah koneksi dari halaman frs_prs menjadi ke halaman nilai, karena saya pikir halaman nilai url nya tidak akan berubah seperti halaman frs. Awalnya kode semester diambil dari halaman frs_prs ini. Kalau coba connect ke url studentportal.unpar.ac.id/frs_prs tidak bisa, bisanya ke restu.unpar.ac.id/frs_prs.
2. Mengambil text kode semester dari halaman nilai.

2020-09-30 09:10 UTC, pascalalfadian requested changes
Hi @davidatz285,

Ada review2 dari saya (ada 5), mohon dicek dan perbaiki ya.

Trims.

2020-09-30 09:10 UTC, pascalalfadian commented on app/models/support/Scraper.java
> -package models.support;
Hi David, ini kalau dicompare di website GitHub nya, jadi kayak dia menghapus 300 baris terus menambahkan 300 baris. Penyebabnya karena kamu mengubah line ending nya dari UNIX ke DOS. Tolong dikembalikan line ending nya jadi UNIX lagi atau coba diatur dari git nya: https://www.edwardthomson.com/blog/git_for_windows_line_endings.html

2020-09-30 09:10 UTC, pascalalfadian commented on app/models/support/Scraper.java
> +	private final String SSO_LOGIN = "https://sso.unpar.ac.id/login?service=https%3A%2F%2Fstudentportal.unpar.ac.id%2FC_home%2Fsso_login";
Ini `SSO_LOGIN` kayaknya tidak terpakai di mana-mana ya? Hapus aja.

2020-09-30 09:10 UTC, pascalalfadian commented on app/models/support/Scraper.java
> +		System.out.println("cur sem = "+curr_sem);
Debugging output mohon dihapus dari kode.

2020-09-30 09:10 UTC, pascalalfadian commented on app/models/support/Scraper.java
> +		for (Element option : options) {
Ini maksudnya mau mengambil elemen terakhir ya? Kalau iya, lebih baik jika ditulis kurang lebih seperti ini biar lebih mudah dipahami:

```
String curr_sem = options.last().val();
```

(dicoba dulu ya soalnya saya nggak compile di sini)

2020-09-30 09:10 UTC, pascalalfadian commented on app/models/support/Scraper.java
> +		Elements options = doc.getElementsByAttributeValue("name", "dropdownSemester").get(0).children();
`get(0)` sepertinya bisa diganti jadi `first()`

2020-10-01 03:27 UTC, pascalalfadian commented
@davidatz285 ini nanti kalau sudah selesai dari sisi kamu tolong infokan saya ya. Kalau ada kesulitan, juga silakan bertanya di sini. Trims.

2020-10-01 03:41 UTC, davidatz285 commented
@pascalalfadian oh iya itu kemarin sore saya rasa udh selesai. Maaf tidak mengabari Pak. Di kode commit 
998c7b8  semua yang diminta di review sudah saya kerjakan. Terima kasih dan mohon maaf.

2020-10-01 08:42 UTC, pascalalfadian commented on app/models/support/Scraper.java
> +		for (Element option : options) {
@davidatz285 tolong optimize sedikit lagi ya, kode ini kan sebenarnya tidak perlu:

```java
String curr_sem = "";
```

2020-10-01 08:44 UTC, pascalalfadian commented
Trims. 4 nya udah oke, 1 lagi tolong diresolve ya.

2020-10-01 09:02 UTC, davidatz285 commented
Sudah diperbaiki sesuai review. Terima kasih.

2020-10-06 06:05 UTC, pascalalfadian approved these changes

2020-10-06 06:06 UTC, pascalalfadian commented
Maaf seperti nya terlewat. Akan saya merge.

2020-10-06 06:06 UTC, merged